from ast import Return
import os, time
from colorama import Fore
print(Fore.BLUE + 'Checking if this script was running on PROOT.' + Fore.RESET)
time.sleep(1.5)
if os.system("pgrep -x 'proot' 2>/dev/null") == True:
    print(Fore.GREEN + 'Yep, It runs on PROOT.' + Fore.RESET)
    time.sleep(1.5)
    os.system('clear')
else:
    print(Fore.RED + "Nope, it wasn't, exiting...." + Fore.RESET)
    time.sleep(1.5)
    os.system('clear')
    exit()

while True:
    print(Fore.BLUE + 'Welcome To Desktop Environment Installer (LXQt Arch Variant) - Python Edition.' + Fore.RESET)
    print('=====================================================')
    print(Fore.RED + 'WARNING! Do not use this script on a real machine.' + Fore.RESET)
    print('=====================================================')
    print('1. Install the DE now. \n2. Multimedia Installer. \n3. About. \n4. Exit.')
    inp1 = input('Your option, sir : ')
    if inp1 == '1':
        print(Fore.BLUE + 'Installing....' + Fore.RESET)
        time.sleep(1.5)
        print(Fore.BLUE + 'Detecting ROOT privileges.' + Fore.RESET)
        time.sleep(1.5)
        if os.system("whoami | root") == True:
            print(Fore.LIGHTRED_EX + 'Installing as ROOT.' + Fore.RESET)
            time.sleep(1.5)
            os.system('pacman -Syu && pacman -S lxqt obconf openbox kvantum')
            print(Fore.GREEN + 'Done, Exiting....' + Fore.RESET)
            time.sleep(1.5)
            os.system('clear')
            exit()
        else:
            print(Fore.LIGHTRED_EX + 'Installing as User.' + Fore.RESET)
            time.sleep(1.5)
            os.system('sudo pacman -Syu && sudo pacman -S lxqt obconf openbox kvantum')
            print(Fore.GREEN + 'Done, Exiting....' + Fore.RESET)
            time.sleep(1.5)
            os.system('clear')
            exit()
    elif inp1 == '2':
        while True:
            os.system('clear')
            print(Fore.BLUE + 'Multimedia Installer.' + Fore.RESET)
            print('======================')
            print('1. Audacious Audio player. \n2. MPV Audio and Video player. \n3. FFMPEG codec support. \n4. All of them. \n5. Exit.')
            inp2 = input('Choose one of them : ')
            if inp2 == '1':
                print(Fore.BLUE + 'Installing....' + Fore.RESET)
                time.sleep(1.5)
                print(Fore.BLUE + 'Detecting ROOT privileges.' + Fore.RESET)
                time.sleep(1.5)
                if os.system("whoami | root") == True:
                    print(Fore.LIGHTRED_EX + 'Installing as ROOT.' + Fore.RESET)
                    time.sleep(1.5)
                    os.system('pacman -Syu && pacman -S audacious audacious-plugins ')
                    print(Fore.GREEN + 'Done, Exiting....' + Fore.RESET)
                    time.sleep(1.5)
                    os.system('clear')
                    exit()
                else:
                    print(Fore.LIGHTRED_EX + 'Installing as User.' + Fore.RESET)
                    time.sleep(1.5)
                    os.system('sudo pacman -Syu && sudo pacman -S audaciuous adacious-plugins')
                    print(Fore.GREEN + 'Done, Exiting....' + Fore.RESET)
                    time.sleep(1.5)
                    os.system('clear')
                    exit()
            elif inp2 == '2':
                print(Fore.BLUE + 'Installing....' + Fore.RESET)
                time.sleep(1.5)
                print(Fore.BLUE + 'Detecting ROOT privileges.' + Fore.RESET)
                time.sleep(1.5)
                if os.system("whoami | root") == True:
                    print(Fore.LIGHTRED_EX + 'Installing as ROOT.' + Fore.RESET)
                    time.sleep(1.5)
                    os.system('pacman -Syu && pacman -S mpv')
                    print(Fore.GREEN + 'Done, Exiting....' + Fore.RESET)
                    time.sleep(1.5)
                    os.system('clear')
                    exit()
                else:
                    print(Fore.LIGHTRED_EX + 'Installing as User.' + Fore.RESET)
                    time.sleep(1.5)
                    os.system('sudo pacman -Syu && sudo pacman -S mpv')
                    print(Fore.GREEN + 'Done, Exiting....' + Fore.RESET)
                    time.sleep(1.5)
                    os.system('clear')
                    exit()
            elif inp2 == '3':
                print(Fore.BLUE + 'Installing....' + Fore.RESET)
                time.sleep(1.5)
                print(Fore.BLUE + 'Detecting ROOT privileges.' + Fore.RESET)
                time.sleep(1.5)
                if os.system("whoami | root") == True:
                    print(Fore.LIGHTRED_EX + 'Installing as ROOT.' + Fore.RESET)
                    time.sleep(1.5)
                    os.system('pacman -Syu && pacman -S ffmpeg')
                    print(Fore.GREEN + 'Done, Exiting....' + Fore.RESET)
                    time.sleep(1.5)
                    os.system('clear')
                    exit()
                else:
                    print(Fore.LIGHTRED_EX + 'Installing as User.' + Fore.RESET)
                    time.sleep(1.5)
                    os.system('sudo pacman -Syu && sudo pacman -S ffmpeg')
                    print(Fore.GREEN + 'Done, Exiting....' + Fore.RESET)
                    time.sleep(1.5)
                    os.system('clear')
                    exit()
            elif inp2 == '4':
                print(Fore.BLUE + 'Installing....' + Fore.RESET)
                time.sleep(1.5)
                print(Fore.BLUE + 'Detecting ROOT privileges.' + Fore.RESET)
                time.sleep(1.5)
                if os.system("whoami | root") == True:
                    print(Fore.LIGHTRED_EX + 'Installing as ROOT.' + Fore.RESET)
                    time.sleep(1.5)
                    os.system('pacman -Syu && pacman -S audacious audacious-plugins ffmpeg mpv')
                    print(Fore.GREEN + 'Done, Exiting....' + Fore.RESET)
                    time.sleep(1.5)
                    os.system('clear')
                    exit()
                else:
                    print(Fore.LIGHTRED_EX + 'Installing as User.' + Fore.RESET)
                    time.sleep(1.5)
                    os.system('sudo pacman -Syu && sudo pacman -S audacious audacious-plugins ffmpeg mpv')
                    print(Fore.GREEN + 'Done, Exiting....' + Fore.RESET)
                    time.sleep(1.5)
                    os.system('clear')
                    exit()
            else:
                print(Fore.RED + 'Unrecognized input.' + Fore.RESET)
                time.sleep(1.5)
                os.system('clear')
    elif inp1 == '3':
        os.system('cat deps/.about')
        resetbutt = ('Press ENTER to exit.')
        exit()
    else:
        print(Fore.RED + 'Unrecognized input.' + Fore.RESET)
        time.sleep(1.5)
        os.system('clear')
